name: build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'
    tags:
      - '*'
  workflow_dispatch: {}

jobs:
  rust-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rust-src, clippy, rustfmt
        override: false

    - name: Install bpf-linker
      run: |
        cargo install bpf-linker

    # TODO: Once we migrate the controller from Go to Rust,
    # add the controller build step here.

    - name: Build all rust crates (dataplane, test server) 
      run: |
        make build

    - name: Check formatting
      run: |
        make check.format

    - name: Check clippy
      run: |
        make lint

    - name: Run Tests
      run: |
        make test
  docker-build:
    name: docker-build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.1.7
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            dataplane:
              - 'dataplane/**'
            containerfile:
              - 'build/Containerfile.dataplane'
      - name: Setup QEMU
        if: steps.filter.outputs.dataplane || steps.filter.outputs.containerfile
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      - name: Setup Docker Buildx
        if: steps.filter.outputs.dataplane || steps.filter.outputs.containerfile
        id: buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
        with:
          buildkitd-flags: "--debug"
      - name: Build multi-arch container image
        if: steps.filter.outputs.dataplane || steps.filter.outputs.containerfile
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          push: false
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          platforms: linux/amd64,linux/arm64
          file: build/Containerfile.dataplane
          tags: kong/blixt-dataplane:pr-${{ github.event.pull_request.number }}-${{ github.sha }}
